# -*- coding: utf-8 -*-
"""A_vysledok.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZrCXHFr5kIUsa8woZ2H9zxJatUzqW9fP
"""

import pandas as pd

root_dir = "/content/drive/MyDrive/"
# base_dir = root_dir + "MPC-VMM/Cviceni/"
base_dir = root_dir + "Colab Notebooks/"

data_path = base_dir + "REPROMEDA/transfery.csv"
# data_path = "/content/drive/MyDrive/Colab Notebooks/Data/"
print(data_path)
data = pd.read_csv(data_path)

# Vytvorenie stĺpca pre vekové kategórie.
bins = [0, 29, 34, 39, float('inf')]
data['vek_mother'] = pd.to_numeric(data['vek_mother'], errors='coerce')
labels = ['do 29', '30-34', '35-39', '40 a výše']
data['vek_kategorie'] = pd.cut(data['vek_mother'], bins=bins, labels=labels, right=False)

# odstránenie nan
df_filtr = data.dropna(subset=['vek_mother', 'clinical_gravidity'])

# Vytvorenie tabuľky úspešnosti v %
tabulka_uspesnosti = df_filtr.groupby(['vek_kategorie', 'clinical_gravidity']).size().unstack().div(
    df_filtr.groupby('vek_kategorie').size(), axis=0) * 100

# Pridanie riadku pre všetky vekové kategórie
tabulka_uspesnosti.loc['všechny věkové kategorie'] = df_filtr.groupby('clinical_gravidity').size() / len(df_filtr) * 100

# Preusporiadanie
tabulka_uspesnosti = tabulka_uspesnosti.reindex(['všechny věkové kategorie'] + labels)

# Premenovanie riadkov a stĺpcov
tabulka_uspesnosti.columns = ['Neúspěch', 'Úspěch']
tabulka_uspesnosti.index.name = 'Věková skupina'

# Vypísanie tabuľky úspešnosti
#print(tabulka_uspesnosti)

# Výpis tabuľky s hodnotami úspešnosti pre jednotlivé vekové kategorie
tabulka_uspesnosti_transp = tabulka_uspesnosti[['Úspěch']].transpose()
tabulka_uspesnosti_transp.columns.name = 'Věková skupina'
print(tabulka_uspesnosti_transp)