# -*- coding: utf-8 -*-
"""B_vysledek.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JYWbrlW89ep2KDGyJi_wZzJsp40GeuCP
"""

import pandas as pd
from scipy.stats import ttest_ind, mannwhitneyu, shapiro, levene

root_dir = "/content/drive/MyDrive/"
base_dir = root_dir + "Colab Notebooks/"

data_path = base_dir + "REPROMEDA/transfery.csv"
data = pd.read_csv(data_path)

# Výpis všetkých unikátnych hodnôt v stĺpci 'vek_mother'
unique_values = data['vek_mother'].unique()
print("Unikátne hodnoty v stĺpci 'vek_mother':", unique_values)

# Prevod 'vek_mother' na numerický formát
data['vek_mother'] = pd.to_numeric(data['vek_mother'], errors='coerce')

# Odstranenie prázdnych hodnot
df_filtr = data.dropna(subset=['vek_mother', 'clinical_gravidity'])

# Rozdelenie dat do dvoch skupin podla 'clinical_gravidity'
group_0 = df_filtr[df_filtr['clinical_gravidity'] == 0]['vek_mother']
group_1 = df_filtr[df_filtr['clinical_gravidity'] == 1]['vek_mother']

# Overenie predpokladu normálneho rozdelenia
statistic_0, p_value_0 = shapiro(group_0)
statistic_1, p_value_1 = shapiro(group_1)

# Overenie predpokladu homogenity variancii
statistic_levene, p_value_levene = levene(group_0, group_1)

# Nastavenie hladiny významnosti
alpha = 0.05

# Kontrola
if p_value_0 > alpha and p_value_1 > alpha and p_value_levene > alpha:
    # Použití t-testu
    statistic, p_value = ttest_ind(group_0, group_1)
    print("T-test:")
else:
    # Použití Mann-Whitneyho testu
    statistic, p_value = mannwhitneyu(group_0, group_1, alternative='two-sided')
    print("Mann-Whitneyho test:")

# Kontrola zamietnutia alebo prijatia nulovej hypotézy pre obe metody
if p_value < alpha:
    print("Nulová hypotéza sa zamietla na hladine významnosti", alpha)
    print("Existuje štatisticky významný rozdiel vo veku matiek medzi dvoma skupinami.")
else:
    print("Nulová hypotéza sa neprijíma na hladine významnosti", alpha)
    print("Rozdiel vo veku matiek medzi skupinami nie je štatisticky významný.")