# -*- coding: utf-8 -*-
"""D_vysledok.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1My-L6wt0tQ2BEvFo6Kv37GCUslaGl5YS
"""

import pandas as pd

root_dir = "/content/drive/MyDrive/"
base_dir = root_dir + "Colab Notebooks/"

data_path = base_dir + "REPROMEDA/transfery.csv"
print(data_path)
data = pd.read_csv(data_path)

# Vytvorenie skupin pre stlpec "genetic_method"
skupiny = {
    'PGT-A': ['PGT-A'],
    'PGT-SR': ['PGT-SR'],
    'Karyomapping': ['Karyomapping'],
    'OneGene': ['OneGene']
}

# Vytvorenie noveho sloupce s názvem "skupina_genetic_method"
data['skupina_genetic_method'] = None

# Priradenie hodnot do noveho sloupce podle skupin
for skupina, hodnoty in skupiny.items():
    mask = data['genetic_method'].isin(hodnoty)
    data.loc[mask, 'skupina_genetic_method'] = skupina

# Identifikace hodnot pro skupinu 'Ostatni'
hodnoty_ostatni = set(data['genetic_method'].unique()) - set([hodnota for hodnoty in skupiny.values() for hodnota in hodnoty])

# Vytvoreni skupiny 'Ostatní'
data.loc[data['genetic_method'].isin(hodnoty_ostatni), 'skupina_genetic_method'] = 'Ostatní'

# Vytvoreni skupiny 'Prázdné hodnoty' pro NaN hodnoty
data.loc[data['genetic_method'].isna(), 'skupina_genetic_method'] = 'Prázdné hodnoty'

# Serazeni sloupcu podle pozadavku
poradi_sloupcu = ['PGT-A', 'PGT-SR', 'Karyomapping', 'OneGene', 'Prázdné hodnoty', 'Ostatní']
tabulka_skupiny_genetic_method = data['skupina_genetic_method'].value_counts().reindex(poradi_sloupcu).reset_index()
tabulka_skupiny_genetic_method.columns = ['skupina_genetic_method', 'Počet']

# Pridani radku s sumou vsech hodnot ve sloupci "Počet"
tabulka_skupiny_genetic_method.loc['Suma'] = tabulka_skupiny_genetic_method['Počet'].sum()

# Transpozice tabulky
tabulka_skupiny_genetic_method_transponovana = tabulka_skupiny_genetic_method.set_index('skupina_genetic_method').transpose()

# Výpis transponovane tabulky
print(tabulka_skupiny_genetic_method_transponovana)