# -*- coding: utf-8 -*-
"""E_vysledok.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nusrgenuaDO3kM_pwXSvRoyUJ4-PK4Fo
"""

import pandas as pd
from scipy.stats import ttest_ind, mannwhitneyu, shapiro, levene

# Nahrani dat
root_dir = "/content/drive/MyDrive/"
base_dir = root_dir + "Colab Notebooks/"

data_path = base_dir + "REPROMEDA/transfery.csv"
data = pd.read_csv(data_path)

# Vylucenie nan
data = data.dropna(subset=['vek_mother', 'clinical_gravidity'])

# rozdelenie dat podle pohlavi
group_0 = data[data['sex'] == 'XX']['clinical_gravidity']
group_1 = data[data['sex'] == 'XY']['clinical_gravidity']

# Overenie predpokladu normalniho rozdeleni
statistic_0, p_value_0 = shapiro(group_0)
statistic_1, p_value_1 = shapiro(group_1)

# Overenie predpokladu homogenity varianci
statistic_levene, p_value_levene = levene(group_0, group_1)

# Nastaveni hladiny vyznamnosti
alpha = 0.05

# Kontrola
if p_value_0 > alpha and p_value_1 > alpha and p_value_levene > alpha:
    # Použití t-testu
    statistic, p_value = ttest_ind(group_0, group_1)
    print("T-test:")
else:
    # Pouziti Mann-Whitneyho testu
    statistic, p_value = mannwhitneyu(group_0, group_1)
    print("Mann-Whitneyho test:")

# Kontrola zamitnuti nebo prijeti nulove hypotezy pro obe metody
if p_value < alpha:
    print("Nulová hypotéza se zamítá na hladině významnosti", alpha)
    print("Existuje statisticky významný rozdíl v úspěchu transferů mezi pohlavím XX a XY.")
else:
    print("Nulová hypotéza se nepřijímá na hladině významnosti", alpha)
    print("Rozdíl v úspěchu transferů mezi pohlavím XX a XY není statisticky významný.")